### ISSUE TITLE
Black box while changing property 

### ISSUE THREAD

**Issue by r-monti14** [gecos-lab/PZero#102]
In all the views, while changing the displayed properties (e.g. none, X, Y, Z, dip_dir, dip and Normals for dips) the box turns black permanently, making the names unreadable. This effect creates no problems in the project and a small blue slider is still visible when selecting a property.
![image](https://github.com/user-attachments/assets/960268c0-2e88-4210-b924-c08ea19700ec)

**Comment by andrea-bistacchi** [comment]
Is this in the PySide6 or PyQt5 environment?

**Comment by r-monti14** [comment]
It's in the PySide6 one, I didn't check for PyQt5

**Comment by andrea-bistacchi** [comment]
Seems ok now.
