### ISSUE TITLE
vedo is not present in the new env

### ISSUE THREAD

**Issue by r-monti14** [gecos-lab/PZero#112]
In the new environment envs/pzero-env.yml , vedo is not present.

**Comment by andrea-bistacchi** [comment]
yes, we do not use it anymore. does it pop up somewhere?

**Comment by andrea-bistacchi** [comment]
Have you updated all? `from vedo import load as vd_load` was removed in the last commit, since we were not using `vedo2vtk.py` (that was broken and has been removed as well) from a long time.

**Comment by r-monti14** [comment]
I think so. I removed all the old envs and installed the new one. I'm also using the latest version of class_refactoring_pyside6. 
I'll try to go deeper into the problem.
