### ISSUE TITLE
Issues with conda install "Solving environment: failed" on Linux (Pop!_OS 21.10)

### ISSUE THREAD

**Issue by gbene** [gecos-lab/PZero#3]
Problems with installing the required packages from the requirements.yml on Pop!_OS 21.10. After running

```bash
conda env create -n pzero -f environment.yml
```

the following error is given:

> Solving environment: failed
    ResolvePackageNotFound: 
      - matplotlib==3.5.1=py38haa244fe_0
      - lerc==3.0=h0e60522_0
      - postgresql==14.1=h1c22c4f_1
      - scikit-learn==1.0.1=py38hb60ee80_3
      - blosc==1.21.0=h0e60522_0
      - brotli-bin==1.0.9=h8ffe710_6
      - kiwisolver==1.3.2=py38hbd9d945_1
      - qt==5.12.9=h5909a2a_4
      - jsoncpp==1.9.4=h2d74725_3
      - libbrotlienc==1.0.9=h8ffe710_6
      - msys2-conda-epoch==20160418=1
      - brotlipy==0.7.0=py38h294d835_1003
      - libxml2==2.9.12=hf5bbc77_1
      - rtree==0.9.7=py38h8b54edf_3
      - libspatialindex==1.9.3=h39d44d4_4
      - libspatialite==5.0.1=hf126459_12
      - vc==14.2=hb210afc_5
      - jxrlib==1.1=h8ffe710_2
      - loguru==0.5.3=py38haa244fe_3
      - cffi==1.15.0=py38hd8c33c5_0
      - vtk==9.1.0=qt_py38h565ee33_203
      - cftime==1.5.1.1=py38h6f4d8f0_1
      - libblas==3.9.0=12_win64_mkl
      - libffi==3.4.2=h8ffe710_5
      - pyproj==3.3.0=py38h12f9802_0
      - libcurl==7.80.0=h789b8ee_1
      - xz==5.2.5=h62dcd97_1
      - vs2015_runtime==14.29.30037=h902a5da_5
      - freetype==2.10.4=h546665d_1
      - poppler==21.11.0=h24fffdf_0
      - cytoolz==0.11.2=py38h294d835_1
      - kealib==1.4.14=h8995ca9_3
      - loopstructural==v1.4.1=py38hb572761_0
      - pugixml==1.11.4=h0e60522_0
      - fonttools==4.28.5=py38h294d835_0
      - yaml==0.2.5=he774522_0
      - libaec==1.0.6=h39d44d4_0
      - libglib==2.70.2=h3be07f2_0
      - python==3.8.12=h7840368_2_cpython
      - geos==3.10.1=h39d44d4_1
      - icu==68.2=h0e60522_0
      - glew==2.1.0=h39d44d4_2
      - importlib-metadata==4.10.0=py38haa244fe_0
      - gl2ps==1.4.2=h0597ee9_0
      - m2w64-gcc-libs==5.3.0=7
      - libpng==1.6.37=h1d00b33_2
      - ucrt==10.0.20348.0=h57928b3_0
      - zfp==0.5.5=h0e60522_8
      - boost-cpp==1.74.0=h5b4e17d_5
      - libcblas==3.9.0=12_win64_mkl
      - libdeflate==1.8=h8ffe710_0
      - fontconfig==2.13.1=h1989441_1005
      - pyqtchart==5.12=py38h885f38d_8
      - m2w64-libwinpthread-git==5.0.0.4634.697f757=2
      - libkml==1.3.0=h9859afa_1014
      - jbig==2.1=h8d14728_2003
      - intel-openmp==2021.4.0=h57928b3_3556
      - pyqt==5.12.3=py38haa244fe_8
      - krb5==1.19.2=h20d022d_3
      - m2w64-gmp==6.1.0=2
      - libwebp-base==1.2.1=h8ffe710_0
      - libbrotlicommon==1.0.9=h8ffe710_6
      - netcdf4==1.5.8=nompi_py38h0500770_101
      - c-blosc2==2.0.4=h09319c2_1
      - libtiff==4.3.0=hd413186_2
      - hdf4==4.2.15=h0e5069d_3
      - openssl==1.1.1l=h8ffe710_0
      - ca-certificates==2021.10.8=h5b45459_0
      - librttopo==1.1.0=he35e8ac_8
      - jpeg==9d=h8ffe710_0
      - proj==8.2.0=h1cfcee9_0
      - pyqtwebengine==5.12.1=py38h885f38d_8
      - libzopfli==1.0.3=h0e60522_0
      - lz4-c==1.9.3=h8ffe710_1
      - brotli==1.0.9=h8ffe710_6
      - pixman==0.40.0=h8ffe710_0
      - snappy==1.1.8=ha925a31_3
      - tiledb==2.5.3=h95dad36_0
      - ffmpeg==4.3.1=ha925a31_0
      - giflib==5.2.1=h8d14728_2
      - xerces-c==3.2.3=h0e60522_4
      - openjpeg==2.4.0=hb211442_1
      - cfitsio==4.0.0=hd67004f_0
      - sqlite==3.37.0=h8ffe710_0
      - wrapt==1.13.3=py38h294d835_1
      - tbb==2021.4.0=h2d74725_1
      - libzip==1.8.0=hfed4ece_1
      - pillow==8.4.0=py38h794f750_0
      - numpy==1.21.5=py38hcf66579_0
      - zstd==1.5.0=h6255e5f_0
      - pyqt-impl==5.12.3=py38h885f38d_8
      - charls==2.2.0=h39d44d4_0
      - scipy==1.7.3=py38ha1292f7_0
      - mkl==2021.4.0=h0e2418a_729
      - pcre==8.45=h0e60522_0
      - utfcpp==3.2.1=h57928b3_0
      - libclang==11.1.0=default_h5c34c98_1
      - double-conversion==3.1.6=h0e60522_0
      - tbb-devel==2021.4.0=h2d74725_1
      - pyqt5-sip==4.19.18=py38h885f38d_8
      - shapely==1.8.0=py38hd784ac2_4
      - unicodedata2==14.0.0=py38h294d835_0
      - pysocks==1.7.1=py38haa244fe_4
      - libnetcdf==4.8.1=nompi_h1cc8e9d_101
      - tornado==6.1=py38h294d835_2
      - certifi==2021.10.8=py38haa244fe_1
      - curl==7.80.0=h789b8ee_1
      - pyyaml==6.0=py38h294d835_3
      - libgdal==3.4.0=hd873378_9
      - geotiff==1.7.0=hc8731e1_5
      - libogg==1.3.4=h8ffe710_1
      - liblapack==3.9.0=12_win64_mkl
      - libssh2==1.10.0=h680486a_2
      - zlib==1.2.11=h8ffe710_1013
      - pandas==1.3.5=py38h5d928e2_0
      - libzlib==1.2.11=h8ffe710_1013
      - expat==2.4.2=h39d44d4_0
      - win_inet_pton==1.1.0=py38haa244fe_3
      - bzip2==1.0.8=h8ffe710_4
      - gettext==0.19.8.1=ha2e2712_1008
      - m2w64-gcc-libgfortran==5.3.0=6
      - lcms2==2.12=h2a16943_0
      - ezdxf==0.17=py38hbd9d945_1
      - markupsafe==2.0.1=py38h294d835_1
      - libbrotlidec==1.0.9=h8ffe710_6
      - imagecodecs==2021.11.20=py38h84a8deb_1
      - libiconv==1.16=he774522_0
      - cairo==1.16.0=hb19e0ff_1008
      - scikit-image==0.19.1=py38h5d928e2_0
      - tk==8.6.11=h8ffe710_1
      - h5py==3.6.0=nompi_py38hde0384b_100
      - libtheora==1.1.1=h8d14728_1005
      - gdal==3.4.0=py38h117dad8_9
      - eigen==3.4.0=h2d74725_0
      - hdf5==1.12.1=nompi_h2a0e4a3_103
      - pywavelets==1.2.0=py38h6f4d8f0_1
      - freexl==1.0.6=ha8e266a_0
      - libpq==14.1=hfcc5ef8_1
      - rasterio==1.2.10=py38h48edd3a_3
      - m2w64-gcc-libs-core==5.3.0=7
      - fiona==1.8.20=py38h19672d5_4
      - cryptography==36.0.1=py38hb7941b4_0
      - matplotlib-base==3.5.1=py38h1f000d6_0
      - setuptools==60.0.3=py38haa244fe_0
      - click==8.0.3=py38haa244fe_1

It could be related to [https://github.com/conda/conda/issues/7311](https://github.com/conda/conda/issues/7311)

**Comment by andrea-bistacchi** [comment]
To be closed due to many improvements on environments.
