### ISSUE TITLE
Switching from Pandas 1.x to 2.x

### ISSUE THREAD

**Issue by mcbaguetti** [gecos-lab/PZero#51]
While I was testing I found that in Pandas 2.0 and above _DataFrame.append()_ was deprecated and [removed](https://pandas.pydata.org/docs/whatsnew/v2.0.0.html#deprecations).
The solution is to use [_.concat(_)](https://stackoverflow.com/questions/76020626/attributeerror-dataframe-object-has-no-attribute-append-for-dataframe) instead of the _append()_ if we want to use a Pandas Version >= 2.0.
But for now, inside environment.yml I would set Pandas <= 2

**Comment by andrea-bistacchi** [comment]
Hi, we have to check the implications. In theory there should be no problem using concat(). Maybe you can make a new branch to test this.

**Comment by andrea-bistacchi** [comment]
This implies some relevant refactoring since, even if append actually is concat in vertical, the syntax is different.

A possible option, also to reduce code repetition, is to define a method in PZero, probably in the ABC class.

**Comment by andrea-bistacchi** [comment]
With 7e6ec423 I started converting all calls of:

`some_dataframe = some_dataframe.append(some_dictionary, ignore_index=True)`

into:

`some_dataframe = pd_concat([some_dataframe, pd_DataFrame(some_dictionary)], ignore_index=True)`

This will allow completely avoiding `append` that is no more allowed in Pandas >= 2.0.0.

**Comment by andrea-bistacchi** [comment]
Closed with 1ea4883e (refactoring pandas) and 5fe6c364 (new environment with pandas > 2).
