### ISSUE TITLE
Code style & formatting

### ISSUE THREAD

**Issue by andrea-bistacchi** [gecos-lab/PZero#55]
Hi, as I progress in my review of existing code I find a mix of different styles, indentation, line termination, commenting using # vs """, etc. 

I guess we better standardize and automate this. There are [PyCharm plug-ins](https://www.jetbrains.com/help/pycharm/reformat-and-rearrange-code.html) based on black, isort or prettier to do this.

Please propose a standard and we will set our IDE and stick to it. This also reduces cosmetic commits.

Regarding commenting, I would propose to use dockstrings (""" ... """) to explain the purpose of functions and classes (one dockstring for each function/class) and standard comments for all other comments.

Thanks!

**Comment by mcbaguetti** [comment]
I think black it's a good choice, Prettier is also nice but better for js/ts files than for python ones

**Comment by andrea-bistacchi** [comment]
Very good! Please give us some instructions in order to have a standard and be able to apply it consistently. This will also reduce commits related to cosmetic changes in the code.

**Comment by mcbaguetti** [comment]
Actually, I have installed black with `conda install black` and then you can run `black <directories or file>` to reformat all the code with the black style. I can check more advanced reformatting options

**Comment by gbene** [comment]
Yes! I really like `black`.

**Comment by andrea-bistacchi** [comment]
ok, let's add it to the pzer onvironments and use it!

**Comment by mcbaguetti** [comment]
added it!

**Comment by mcbaguetti** [comment]
yes, I think it's a good option for PyCharm if you want to use black automatically on your computer

**Comment by andrea-bistacchi** [comment]
I installed black in the conda environment
```
conda activate pzero
conda install blackd
```

Then I installed the PyCharm Plugin BlackConnect with File > Plugins > search "black connect" > Install.

Then I edited BlackConnect settings from File > Settings > Tools > BlackConnect  as follows:

![image](https://github.com/andrea-bistacchi/PZero/assets/12087912/baff79ce-bd19-422f-b307-e40dd0a9de79)

Now I find BlackConnect under Tools:

![image](https://github.com/andrea-bistacchi/PZero/assets/12087912/a9523e08-339d-49eb-9e53-a805b8e66825)

But it does not appear to modify files.

Suggestions?

**Comment by mcbaguetti** [comment]
are you inside the main branch? because I've already pushed the reformatting process with black. I did exactly the same steps as you and it worked

**Comment by gbene** [comment]
For me it works also on the AB_GUI_tests branch. I noticed that it took a bit the first time that I tested it

**Comment by andrea-bistacchi** [comment]
We must make this a standard in instructions for developers.

**Comment by andrea-bistacchi** [comment]
This is the standard now, as explained in https://github.com/gecos-lab/PZero/wiki/PZero-code-style-&-formatting.
