### ISSUE TITLE
Error in importing DEM. Maybe can be fixed by rioxarray instead of using rasterio as an engine. 

### ISSUE THREAD

**Issue by waqashussain117** [gecos-lab/PZero#96]
Error in importing DEM files to PZERO:

The error message indicates that xarray does not recognize 'rasterio' as a valid engine. This usually happens when the 'rasterio' backend is not registered with xarray.
In recent versions of xarray (0.18 and above), the way to read raster files (like GeoTIFFs) has changed.
Solution in the new version is to import rioxarray.

**Comment by waqashussain117** [comment]
To fix this issue, we should use rioxarray.open_rasterio() instead of xr.open_dataset(). The function rioxarray.open_rasterio() returns an xarray.DataArray represents a single raster band and has a .values attribute that we can use to access the raster data directly.

two lines of code changed:

data = xr.open_dataset(in_file_name, engine='rasterio')
to
data = rioxarray.open_rasterio(in_file_name)

and in order to access the raster data. We should use data.values instead of data.data
so changing

values = data.values[0]  # Assuming single-band raster

**Comment by waqashussain117** [comment]
Fixed

**Comment by andrea-bistacchi** [comment]
FIxed in `class_refactoring` branch.
